name: kaktwoos-rs-build-linux-arm64

on: [push]

jobs:
    arm64_build:
      name: kaktoos-rs/release/arm64-linux
      runs-on: [ubuntu-latest]
      steps:
        - uses: actions/checkout@v2
        - uses: actions-rs/toolchain@v1
          with:
            toolchain: stable
        - run: |
            sudo apt-get install gcc-aarch64-linux-gnu g++-aarch64-linux-gnu gcc g++ make m4 pkg-config build-essential autoconf libtool cmake
            rustup target add aarch64-unknown-linux-gnu
            cp config ~/.cargo/config
            cargo build --target=aarch64-unknown-linux-gnu
            mkdir ./bin
            cp ./target/aarch64-unknown-linux-gnu/debug/libkaktwoos_rs.so ./bin/
            file bin/libkaktwoos_rs.so
            aarch64-linux-gnu-g++ -O3 -o kaktwoos-rs main.cc bin/libkaktwoos_rs.so -Wall -Wextra -Iboinc/ -Lboinc/lib/arm64 -static-libgcc -static-libstdc++ -lboinc_api -lboinc -lboinc_opencl -pthread -Wl,-dynamic-linker,/lib64/ld-linux-x86-64.so.2          
            ls -ls
        - uses: actions/upload-artifact@v2
          with:
            name: kaktwoos-rs-lin
            path: ./kaktwoos-rs*
         
